### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-blog#2]
Main welcome: bitcartcc/bitcart#133

Issue list:
- [x] Fix favicon barely visible in darkmode (#3)
- [x] Feat: Clicking post image or title should ref to it's article (#1)
- [x] Fix image sizing issues (#6)

**Comment by orestischaral** [comment]
Hey, Can I work on this issue?

**Comment by orestischaral** [comment]
@MrNaif2018 I ve resolved the issue. You can assign me this issue to push.

**Comment by MrNaif2018** [comment]
Hi! Thank you! Sure! This issue is an issue list for all issues in a repo, you should comment on individual issues for me to assign you to them. Also assigning is not required too, feel free to open PR and I'll review it.
<strike>Note: the issue in the list is pointing to a wrong one, I'll fix it now</strike> Done

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest!
